Fixing simva infrastructure
e-ucm/simva-infra pull request #24
Opened 2024-05-20 12:33 UTC by jujusb

2024-05-22 18:11 UTC, imartinezortiz commented
Things to address before merging the PR:
 - [ ] Portainer stack should be only available in the development environment. This includes both portainer and dozzle. For dozzle we can think about to enable it in production, but must use the **docker-socket-proxy** approach to mitigate security issues (see 01-traefik stack).
 - [ ] Anaconda should be only available in development environment or the administrator should manually enable it in simva-env.sh. The the stack is not designed for allowing Jupyter / Anaconda to be used by multiple users.

The PR is quite large. It will take me some time to review it

2024-05-22 19:10 UTC, imartinezortiz requested changes
good work !. There are some changes to address before merging

2024-05-22 19:10 UTC, imartinezortiz commented on docker-stacks/06-simva/etc/hooks/purge.d/01-remove-data-and-config.sh
> +cd "${SIMVA_DATA_HOME}/simva/puppeteer" && rm -rf ./*
Umm, do not remember why puppeteer this is needed, shouldn't be required. Open an issue to track the discussion

2024-05-22 19:10 UTC, imartinezortiz commented on docker-stacks/09-portainer/docker-compose.dozzle.yml
> +      DOZZLE_KEY: s3cr3ts1mv4
These should be configurable

2024-05-22 19:10 UTC, imartinezortiz commented on docker-stacks/etc/hooks/before-install.d/20-install-gomplate.sh
> +    # Set the default download URL and SHA256SUMS URL
maybe it is interesting to move thise to simva-evn.sh so the OS and ARCHITECHTURE env variables are available for all scripts

2024-05-23 10:30 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/after-start.d/00-wait-keycloak-available.sh
> +#!/usr/bin/env bash
It's needed for the upgrade process to wait until the upgrade is done before continue in the process.

2024-05-23 10:34 UTC, jujusb commented on docker-stacks/06-simva/etc/hooks/purge.d/01-remove-data-and-config.sh
> +cd "${SIMVA_DATA_HOME}/simva/puppeteer" && rm -rf ./*
This is needed to save the cache of the broswer data for the pdf generation of user in SIMVA.

2024-05-23 10:36 UTC, jujusb commented on docker-stacks/01-traefik/etc/hooks/after-start.d/10-wait-available.sh
> +#fi;
This is on purpose because we need to change the process for the SIMVA_TRAEFIK_DASHBOARD_PASSWORD because it's a password hashed, so we can't use this script to check that Traefik is available. This is in process in another branch.

2024-05-23 11:28 UTC, jujusb commented on docker-stacks/01-traefik/docker-compose.yml
> +            #contentSecurityPolicy = "frame-src 'self' https://${SIMVA_EXTERNAL_DOMAIN:-external.test} https://*.${SIMVA_EXTERNAL_DOMAIN:-external.test}; frame-ancestors 'self' https://${SIMVA_EXTERN
It's enabled again.

2024-05-23 13:41 UTC, jujusb commented on docker-stacks/01-traefik/docker-compose.yml
> +    image: ${SIMVA_TRAEFIK_IMAGE:-traefik}:${SIMVA_TRAEFIK_VERSION:-3.0.0}
Revert to version 2.11.3 because traefik 3.0 introduce changes.

2024-05-23 13:45 UTC, jujusb commented on docker-stacks/09-portainer/docker-compose.dozzle.yml
> +      DOZZLE_KEY: s3cr3ts1mv4
Those are now configurable.

2024-05-23 14:07 UTC, jujusb commented on docker-stacks/01-traefik/docker-compose.dev-lb.yml
>        SIMVA_DNS_SERVICE_IP: ${SIMVA_DNS_SERVICE_IP:-172.30.0.53}
not needed anymore. Removing it

2024-05-24 09:32 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/after-start.d/20-wait-keycloak-available.sh
> +#!/usr/bin/env bash
This one is for checking that the SIMVA Realm is available. This one has been renamed for a better understanding

2024-05-24 09:38 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/before-install.d/40-prepare-realm-config.sh
> +# #################################
removed

2024-05-24 11:37 UTC, jujusb commented on docker-stacks/etc/hooks/before-install.d/20-install-gomplate.sh
> +    # Set the default download URL and SHA256SUMS URL
Those are now in simva-env.sh

2024-05-24 12:54 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/before-install.d/10-checkout-code.sh
> +#!/usr/bin/env bash
issue opened

2024-05-24 14:39 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/before-install.d/40-prepare-realm-config.sh
>          done < <(${SIMVA_HOME}/bin/pbkdf2 -b64 -l 64 -i 27500 -j ${user_password})
Opened an issue about it

2024-05-24 14:44 UTC, jujusb commented on docker-stacks/01-traefik/docker-compose.dev-lb.yml
>      image: nginx:1.19.2
I never used in dev the load balancer, so I don't know how to check that.

2024-05-28 10:35 UTC, imartinezortiz requested changes

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/05-kafka/etc/hooks/before-install.d/20-generate-config-file-kafka-ui.sh
> +echo "options edns0 ndots:0" >>"${SIMVA_CONFIG_HOME}/kafka/topics-ui/resolv.conf"
docker internal dns resolver is 127.0.0.11 so it is not required to do anything. Besides, changing manually resolv.conf inside a container it is not something normal. Seems to me that there is an issue to solve.

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/05-kafka/etc/hooks/before-migrateDomain.d/10-migrateDomain.sh
downcaes script

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/05-kafka/etc/hooks/purge.d/01-remove-data-and-config.sh
See previous comments regarding rm -fr

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/05-kafka/etc/hooks/purge.d/02-remove-extensions-target.sh
See previous comments regarding rm -fr

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/06-simva/README.md
> +ssh  -L0.0.0.0:9092:localhost:9092 -N vagrant@192.168.253.2
Keep the previous example. It is done on purpose, to avoid warning / errors during development.

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/06-simva/docker-compose.localdev.yml
This script should be updated, dns-proxy-server it is not used anymore

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/06-simva/etc/hooks/after-start.d/10-wait-SIMVA-Front-available.sh
downcase script

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/06-simva/etc/hooks/after-start.d/20-wait-SIMVA-API-available.sh
downcase script

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/06-simva/etc/hooks/purge.d/01-remove-data-and-config.sh
see previous comments regarding rm -fr

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/08-anaconda/etc/hooks/purge.d/01-remove-data-and-config.sh
see previous comment regarding rm -fr *

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/09-logs/etc/hooks/purge.d/01-remove-data-and-config.sh
see previous rm -fr comment

2024-05-28 10:35 UTC, imartinezortiz commented on docker-stacks/09-logs/docker-compose.dozzle.yml
> +      - /var/run/docker.sock:/var/run/docker.sock:ro
Previous PR review raised the issue regarding the access of dozzle to the docker socket. Address in a similar way as used in traefik stack, because dozzle is still used in production (looking into simva-env.sh)

2024-05-28 11:02 UTC, imartinezortiz commented
Reviewing the PR is PITA due to to the GH UI being sluggish as hell and the gazillion commits and changed files. Please, open a different PR that sends changes to the base branch used for this PR, so changes are more easy to follow.

Moreover, I suggest to squash the PR before the merge, due to the amount of commits and because I do not expect to revert any of this commit in an isolated way.

Just a quick reminder, that Included as part of the current review, but that is applicable to the new (and old) bash scripts:
-  The ${XXXX:-default} syntax is usually used in compose files because is the only applicable syntax. However bash has a more [rich parameter substitution](https://tldp.org/LDP/abs/html/parameter-substitution.html). For bash scripts seems more use to use
```bash
# at the begging of the script
: ${VAR:= default value}
...
${VAR}
```
- Use a safer approach in bash script development [^1]. So do not disable / comment out scripts prelude and add it in new scripts.


[^1]: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

2024-05-28 15:58 UTC, jujusb commented on docker-stacks/01-traefik/etc/hooks/after-start.d/10-wait-available.sh
> +#[[ "${DEBUG:-false}" == "true" ]] && set -x
done

2024-05-28 15:58 UTC, jujusb commented on docker-stacks/01-traefik/etc/hooks/before-start.d/10-configure-traefik.sh
> +chmod -R 777 "${SIMVA_CONFIG_HOME}/traefik/traefik/static-conf/"
fixed

2024-05-28 15:59 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/after-migrate.d/10-MigrateRealm-with-all-users-and-clients.sh
fixed

2024-05-29 06:46 UTC, jujusb commented on docker-stacks/01-traefik/docker-compose.yml
> +              "${SIMVA_TRAEFIK_DASHBOARD_USER:?Traefik dashboard username must be configured}:$(cat "/data/traefik-password-hashed.txt")"
done

2024-05-29 06:47 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/before-install.d/13-build-kcadm-KEYCLOAK-14595.sh
It is still needed for the migration process

2024-05-29 06:47 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/before-install.d/20-Update-SIMVA-theme.sh
fixed

2024-05-29 06:49 UTC, jujusb commented on docker-stacks/06-simva/README.md
> +ssh  -L0.0.0.0:9092:localhost:9092 -N vagrant@192.168.253.2
revert to the previous example

2024-05-29 06:56 UTC, jujusb commented on docker-stacks/02-keycloak/etc/hooks/before-install.d/40-prepare-realm-config.sh
> +    users="student teaching_assistant teacher researcher administrator"
It is intentional and it don't break anything

2024-05-29 06:56 UTC, jujusb commented on docker-stacks/05-kafka/etc/hooks/before-install.d/20-generate-config-file-kafka-ui.sh
> +echo "options edns0 ndots:0" >>"${SIMVA_CONFIG_HOME}/kafka/topics-ui/resolv.conf"
removed

2024-05-29 07:00 UTC, jujusb commented on docker-stacks/06-simva/docker-compose.localdev.yml
updated

2024-05-29 07:10 UTC, jujusb commented on docker-stacks/02-keycloak/extensions/simva-lti/docker-compose.yaml
fix

2024-05-29 07:13 UTC, jujusb commented on docker-stacks/02-keycloak/extensions/simva-lti/README.md
moved into wiki

2024-06-03 10:05 UTC, jujusb commented on docker-stacks/01-traefik/etc/hooks/before-install.d/20-checkout-code.sh
> +    # Calculate checksums of package.json and package-lock.json
issue opened

2024-06-04 08:58 UTC, jujusb commented on docker-stacks/05-kafka/etc/hooks/before-install.d/20-generate-config-file-kafka-ui.sh
> +echo "options edns0 ndots:0" >>"${SIMVA_CONFIG_HOME}/kafka/topics-ui/resolv.conf"
fixed using provectuslabs/kafka-ui instead that contain Connect UI, Topic UI, Schema Registry

2024-06-04 09:25 UTC, jujusb commented on docker-stacks/09-logs/docker-compose.dozzle.yml
> +      - /var/run/docker.sock:/var/run/docker.sock:ro
fixed

2024-06-19 14:00 UTC, merged